apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
    imagePullSecret:
    - name: my-docker-secret #from secret file
      containers:
      - name: my-app-container
        # image: put aws image name
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
