controller:
  replicaCount: 2
  service:
    type: LoadBalancer  # You can change this to NodePort or ClusterIP
    externalTrafficPolicy: Local
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
