apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "delete"]
# ClusterRoles are similar to Roles but are used across 
    # the entire cluster (not just in a single namespace).