apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # "mongoadmin" base64 encoded
  mongo-root-password: bW9uZ29wYXNz  # "mongopass" base64 encoded

#to creat such password in terminal >> echo -n 'username' | base64  >>>>>bW9uZ29hZG1pbg>>>>>